version: 2
updates:

  # Github Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  # poster
  - package-ecosystem: npm
    directory: "/poster/"
    schedule:
      interval: monthly

  # web
  - package-ecosystem: npm
    directory: "/web/"
    schedule:
      interval: monthly
