name: Save pages to Web Archive's Wayback Machine

on:
  workflow_run:
    workflows:
      - Deploy website
    types:
      - completed
  workflow_dispatch:

permissions:
  contents: read

jobs:
  preserve:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Get web-archiver
        run: |
          curl https://github.com/iyaki/web-archiver/releases/latest/download/web-archiver_Linux_x86_64 -Lo web-archiver
          chmod +x ./web-archiver
      - name: Save pages to Web Archive's Wayback Machine
        env:
          WAYBACK_S3_ACCESS_KEY: ${{ secrets.WAYBACK_S3_ACCESS_KEY }}
          WAYBACK_S3_SECRET_KEY: ${{ secrets.WAYBACK_S3_SECRET_KEY }}
        run: |
          TODAY="$(date -I)"
          ./web-archiver https://iyaki.ar/sitemap.xml "${TODAY}"
